title: www.gepr.eu
titles:
  fr: "www.rgpe.eu" 
  en: "www.gepr.eu"
email: info@gepr.eu
description: >-
  Our earth needs protection too. We invite companies to take
  environment protection as seriously as data protection and
  take actions.
baseurl: ""
url: "http://www.gepr.eu"
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
